version: "3"
services:
  server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      - CLICKHOUSE_DB=trp
      - CLICKHOUSE_USER=trp_user
      - CLICKHOUSE_PASSWORD=trppassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
    - db_data:/var/lib/clickhouse/
    - .:/data
    - ./conf/server/config.xml:/etc/clickhouse-server/config.xml
volumes:
  db_data:
    driver: local
  db_config:
    driver: local