version: "3"
services:
  server:
    container_name: ch-server
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
    - db_data:/var/lib/clickhouse/
    - .:/data
    - ./conf/users/:/etc/clickhouse-server/users.d/
    - ./conf/server/:/etc/clickhouse-server/config.d/
volumes:
  db_data:
    driver: local
  db_config:
    driver: local