version: "3"
services:
  server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
    - db_data:/var/lib/clickhouse/
    - .:/data
volumes:
  db_data:
    driver: local
  db_config:
    driver: local